export interface Country {
  label: string;
  name: string;
  value: string;
}

export const countryOptions: Country[] = [
  { label: "Australia", name: "Australia", value: "au" },
  { label: "Brazil", name: "Brazil", value: "br" },
  { label: "Canada", name: "Canada", value: "ca" },
  { label: "China", name: "China", value: "cn" },
  { label: "France", name: "France", value: "fr" },
  { label: "Germany", name: "Germany", value: "de" },
  { label: "India", name: "India", value: "in" },
  { label: "Japan", name: "Japan", value: "jp" },
  { label: "United Kingdom", name: "UK", value: "uk" },
  { label: "United States", name: "USA", value: "us" },
  { label: "Argentina", name: "Argentina", value: "ar" },
  { label: "Spain", name: "Spain", value: "es" },
  { label: "Italy", name: "Italy", value: "it" },
  { label: "Mexico", name: "Mexico", value: "mx" },
  { label: "South Korea", name: "South Korea", value: "kr" },
  { label: "Russia", name: "Russia", value: "ru" },
  { label: "Netherlands", name: "Netherlands", value: "nl" },
  { label: "Switzerland", name: "Switzerland", value: "ch" },
  { label: "Sweden", name: "Sweden", value: "se" },
  { label: "New Zealand", name: "New Zealand", value: "nz" },
  { label: "Norway", name: "Norway", value: "no" },
  { label: "Denmark", name: "Denmark", value: "dk" },
  { label: "Portugal", name: "Portugal", value: "pt" },
  { label: "Belgium", name: "Belgium", value: "be" },
  { label: "Austria", name: "Austria", value: "at" },
  { label: "Greece", name: "Greece", value: "gr" },
  { label: "Turkey", name: "Turkey", value: "tr" },
  { label: "Singapore", name: "Singapore", value: "sg" },
  { label: "Hong Kong", name: "Hong Kong", value: "hk" },
  { label: "Thailand", name: "Thailand", value: "th" },
  { label: "Vietnam", name: "Vietnam", value: "vn" },
  { label: "Malaysia", name: "Malaysia", value: "my" },
  { label: "Philippines", name: "Philippines", value: "ph" },
  { label: "Indonesia", name: "Indonesia", value: "id" },
  { label: "Saudi Arabia", name: "Saudi Arabia", value: "sa" },
  { label: "United Arab Emirates", name: "UAE", value: "ae" },
  { label: "South Africa", name: "South Africa", value: "za" },
  { label: "Egypt", name: "Egypt", value: "eg" },
  { label: "Morocco", name: "Morocco", value: "ma" },
  { label: "Kenya", name: "Kenya", value: "ke" },
  { label: "Nigeria", name: "Nigeria", value: "ng" },
  { label: "Ghana", name: "Ghana", value: "gh" },
  { label: "Peru", name: "Peru", value: "pe" },
  { label: "Chile", name: "Chile", value: "cl" },
];

export const fruitOptions: string[] = [
  "Apple",
  "Avocado",
  "Banana",
  "Blueberry",
  "Cantaloupe",
  "Cherry",
  "Date",
  "Dragonfruit",
  "Elderberry",
  "Fig",
  "Grape",
  "Guava",
  "Honeydew",
  "Jackfruit",
  "Kiwi",
  "Kumquat",
  "Lemon",
  "Lychee",
  "Mango",
  "Nectarine",
  "Orange",
  "Papaya",
  "Passionfruit",
  "Pineapple",
  "Quince",
  "Rambutan",
  "Raspberry",
  "Starfruit",
  "Strawberry",
  "Tangerine",
  "Ugli fruit",
  "Watermelon",
  "Xigua (Chinese watermelon)",
  "Yuzu",
  "Zucchini",
  "Apricot",
  "Blackberry",
  "Coconut",
  "Cranberry",
  "Durian",
  "Elderberry",
  "Figs",
  "Gooseberry",
  "Grapefruit",
  "Huckleberry",
  "Jujube",
  "Mulberry",
  "Peach",
  "Plum",
  "Pomegranate",
  "Rutabaga",
  "Soursop",
];
